# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeremy Roelfs
email: jeremyroelfs@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  We are programmers, designers, hackers, makers, tinkerers, 
  writers and artists and we want to have an impact on the community 
  around us.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeremyroelfs.com" # the base hostname & protocol for your site

twitter_username: The_J_Roel
github_username:  J-Roel

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

